// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which effect to put behind a window.
 */
export type EffectKind = "none" | "blur" | "mica" | "acrylic";
