// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectKind } from "./EffectKind";
import type { Rect } from "./Rect";

/**
 * What `apply` puts behind a window. How see-through the window is stays the page's own alpha: the effect only shows through where the page is transparent.
 */
export type Effects = { kind: EffectKind, 
/**
 * The page is dark: picks the dark Mica, and the tint of Blur and Acrylic on Windows.
 */
dark: boolean, 
/**
 * Where on the window to blur (Linux). Absent means the whole window. Windows effects always cover the whole window.
 */
region: Array<Rect> | null, };
