// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The margin, in logical pixels, a client-side shadow or an invisible resize border takes around the window's visible area. The compositor leaves it out of the window's geometry, so a tiled or snapped window sits flush with its neighbours and the screen edge.
 */
export type Insets = { top: number, right: number, bottom: number, left: number, };
