// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";
import type { Flavour } from "./Flavour";
import type { Reason } from "./Reason";

/**
 * What the plugin can do on the running system.
 */
export type PluginStatus = { 
/**
 * True when at least one feature is available.
 */
available: boolean, 
/**
 * Why something this system could do is missing: the first unavailable feature's reason, leaving out features that belong to another platform (Mica on Linux, the shadow inset on Windows). Absent when everything that applies works.
 */
reason: Reason | null, message: string | null, flavour: Flavour, features: Array<FeatureStatus>, };
