// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rectangle in the window's own logical pixels, from its top left.
 */
export type Rect = { x: number, y: number, width: number, height: number, };
