// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reason } from "./Reason";

/**
 * Why a request failed. Serialised as `{ "kind": "unsupported", "reason": "compositor-has-no-blur", "message": "…" }`, so the front end can branch on `kind` and `reason`.
 */
export type WindowEffectsError = { "kind": "unsupported", reason: Reason, message: string, } | { "kind": "windowNotFound", label: string, } | { "kind": "invalidRegion", message: string, } | { "kind": "invalidInsets", message: string, } | { "kind": "failed", message: string, };
