// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashError } from "./TrashError";

/**
 * One item `empty` could not remove.
 */
export type EmptyFailure = { trashId: string, error: TrashError, };
