// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmptyFailure } from "./EmptyFailure";

/**
 * What `empty` did. Items that could not be removed are reported and left in the trash; the rest are still removed.
 */
export type EmptyReport = { 
/**
 * How many items were removed.
 */
removed: number, failed: Array<EmptyFailure>, };
