// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one feature of the plugin works on this system.
 */
export type FeatureStatus = { 
/**
 * One of `trash`, `list`, `restore`, `empty`, `expiry` or `per-volume`.
 */
name: string, available: boolean, 
/**
 * Why the feature is unavailable or degraded; absent when it works fully.
 */
reason: string | null, };
