// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which implementation is behind the plugin on this system.
 */
export type Flavour = "freedesktop" | "portal" | "windows" | "unsupported";
