// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where `restore` puts an item.
 */
export type RestoreTarget = { "kind": "original" } | { "kind": "path", path: string, };
