// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashError } from "./TrashError";
import type { TrashReceipt } from "./TrashReceipt";

/**
 * The result of trashing one path of a batch.
 */
export type TrashOutcome = { "status": "trashed", receipt: TrashReceipt, } | { "status": "failed", error: TrashError, };
