// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one trash operation failed. Serialised as `{ "kind": "originExists", "path": "…" }`, so the front end can branch on `kind` and prompt (for example to restore somewhere else).
 */
export type TrashError = { "kind": "notFound" } | { "kind": "permissionDenied" } | { "kind": "trashUnavailable", reason: string, } | { "kind": "refused", reason: string, } | { "kind": "originExists", path: string, } | { "kind": "originMissingParent", path: string, } | { "kind": "unsupported" } | { "kind": "io", message: string, };
