// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proof that something was trashed, and the handle to restore or delete it later.
 */
export type TrashReceipt = { 
/**
 * A stable id for the item: the trash it is in plus its name there on Linux, the Recycle Bin item's path on Windows. It stays valid across restarts and other apps, until the item leaves the trash.
 */
trashId: string, 
/**
 * Where the item was before it was trashed.
 */
originalPath: string, 
/**
 * When it was trashed, in seconds since the Unix epoch.
 */
deletedAt: number, };
