// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrashReceipt } from "./TrashReceipt";

/**
 * One item in the trash.
 */
export type TrashedItem = { receipt: TrashReceipt, 
/**
 * The item's name before it was trashed (the trash itself may have renamed it to be unique).
 */
name: string, originalPath: string, 
/**
 * When it was trashed, in seconds since the Unix epoch.
 */
deletedAt: number, 
/**
 * Size in bytes; for a folder, the total of the files in it.
 */
size: number, 
/**
 * True for a folder (not for a link to one).
 */
isDir: boolean, };
