// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Android's Developer Options "Animator duration scale"; always 1 off Android.
 */
export type AnimatorDurationScaleResponse = { scale: number, };
