// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";
import type { TimeFormatSource } from "./TimeFormatSource";

/**
 * What the plugin can do on the running system.
 */
export type PluginStatus = { 
/**
 * True when at least one feature is available.
 */
available: boolean, 
/**
 * Why nothing is available; absent otherwise.
 */
reason: string | null, features: Array<FeatureStatus>, 
/**
 * Where the current time format comes from; absent when it has not been read.
 */
timeFormatSource: TimeFormatSource | null, };
