// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the reported time format came from.
 */
export type TimeFormatSource = "gnome-portal" | "gnome-gsettings" | "cinnamon-gsettings" | "locale" | "windows-user-locale" | "windows-fallback" | "macos-date-template" | "ios" | "android" | "default";
