// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeFormatSource } from "./TimeFormatSource";

/**
 * The user's 12/24-hour clock preference.
 *
 * This is the payload of `get_time_format` and of the `os-prefs://time-format-changed` event. The
 * `is24Hour` field is the original wire shape of the mobile plugin; `source` is additive and is
 * filled in by the Rust side on every platform.
 */
export type TimeFormat = { is24Hour: boolean, source: TimeFormatSource, };
