// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The windowing system the app is running under.
 */
export type Session = "wayland" | "x11" | "windows" | "macos" | "unknown";
