// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Session } from "./Session";

/**
 * Window manager features that work on this system.
 */
export type WindowCapabilities = { session: Session, 
/**
 * Whether the app can keep a window above others itself. False on Wayland, where only the compositor's own window menu can do it.
 */
alwaysOnTop: boolean, 
/**
 * Whether `show_system_window_menu` can ask the compositor for its window menu.
 */
systemWindowMenu: boolean, };
