// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The files on the clipboard.
 */
export type ClipboardFiles = { 
/**
 * The `file://` URIs.
 */
uris: Array<string>, 
/**
 * True if the files were cut (to be moved on paste), false if copied.
 */
cut: boolean, };
