// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The windowing system the plugin found.
 */
export type DisplayServer = "wayland" | "x11" | "windows" | "none";
