// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an outbound drag may do with the files.
 */
export type DragAction = "copy" | "move" | "link";
