// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DragOutcome } from "./DragOutcome";

/**
 * Sent when an outbound drag ends, and returned by `start_drag` where the drag has already ended by the time the command resolves.
 */
export type DragEnded = { 
/**
 * The `id` `start_drag` returned for the drag.
 */
id: number, outcome: DragOutcome, 
/**
 * The URIs that were offered.
 */
uris: Array<string>, 
/**
 * Why the drag failed, for `failed`.
 */
reason: string | null, };
