// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A drag image, as the bytes of a PNG file.
 */
export type DragIcon = { png: Array<number>, };
