// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DragAction } from "./DragAction";
import type { Modifiers } from "./Modifiers";
import type { Position } from "./Position";

/**
 * Sent when files are dropped on a window.
 */
export type DropEvent = { window: string, paths: Array<string>, uris: Array<string>, position: Position, modifiers: Modifiers, 
/**
 * See [`EnterEvent::action`].
 */
action: DragAction | null, 
/**
 * True if the drop is the end of an outbound drag this process started with `start_drag`; `uris` are then exactly the ones that were offered.
 */
selfDrop: boolean, };
