// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Modifiers } from "./Modifiers";
import type { Position } from "./Position";

/**
 * Sent when files first move over a window.
 */
export type EnterEvent = { 
/**
 * The label of the window the files are over.
 */
window: string, 
/**
 * The files as display strings; a name that is not valid Unicode is shown with replacement characters and cannot be reopened from this value, use `uris` for that.
 */
paths: Array<string>, 
/**
 * The files as `file://` URIs with every byte outside `A-Za-z0-9-._~/` percent-encoded, so a name that is not valid Unicode survives.
 */
uris: Array<string>, position: Position, modifiers: Modifiers, };
