// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DragAction } from "./DragAction";
import type { Modifiers } from "./Modifiers";
import type { Position } from "./Position";

/**
 * Sent when files first move over a window.
 */
export type EnterEvent = { 
/**
 * The label of the window the files are over.
 */
window: string, 
/**
 * The files as display strings; a name that is not valid Unicode is shown with replacement characters and cannot be reopened from this value, use `uris` for that.
 */
paths: Array<string>, 
/**
 * The files as `file://` URIs with every byte outside `A-Za-z0-9-._~/` percent-encoded, so a name that is not valid Unicode survives.
 */
uris: Array<string>, position: Position, modifiers: Modifiers, 
/**
 * The action the drag has been negotiated to, where the platform reports one (GTK: on Wayland the drag context's selected action, which the compositor sets, and on X11 its suggested action, kept to what the source offers). On Wayland the compositor chooses it from the keys it holds, which the app cannot read, so Shift reads as `move` here and nowhere else. `null` where nothing is reported (Windows, which reports modifiers instead) or the platform names no action a drop can take.
 */
action: DragAction | null, };
