// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kinds of failure a command reports.
 */
export type ErrorKind = "unsupported" | "buttonNotPressed" | "alreadyActive" | "keysHeld" | "invalid" | "failed";
