// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";

/**
 * Every feature the plugin reports.
 */
export type Features = { 
/**
 * Normalised `enter`, `over`, `drop` and `leave` events for windows whose drag-drop handler is on.
 */
inbound: FeatureStatus, 
/**
 * `start_drag`.
 */
outbound: FeatureStatus, 
/**
 * Inbound positions in logical pixels.
 */
positions: FeatureStatus, 
/**
 * Modifier keys read at event time.
 */
modifiers: FeatureStatus, 
/**
 * `set_files`, `get_files` and the clipboard event.
 */
clipboard: FeatureStatus, 
/**
 * Telling a drop of this process's own outbound drag from a drop from another application.
 */
"self-drop-filter": FeatureStatus, };
