// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one feature works.
 */
export type FeatureStatus = { available: boolean, 
/**
 * Why the feature does not work, when `available` is false.
 */
reason: string | null, };
