// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent when files leave a window without being dropped.
 */
export type LeaveEvent = { window: string, };
