// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The modifier keys held when an event happened.
 */
export type Modifiers = { ctrl: boolean, shift: boolean, 
/**
 * Alt on Windows and Linux (Option elsewhere).
 */
alt: boolean, };
