// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * The value a failed command rejects with.
 */
export type NativeDndError = { kind: ErrorKind, message: string, };
