// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Modifiers } from "./Modifiers";
import type { Position } from "./Position";

/**
 * Sent as files move over a window.
 */
export type OverEvent = { window: string, position: Position, modifiers: Modifiers, };
