// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayServer } from "./DisplayServer";
import type { Features } from "./Features";

/**
 * What `get_status` reports.
 */
export type PluginStatus = { 
/**
 * True if at least one feature works.
 */
available: boolean, 
/**
 * Why nothing works, when `available` is false.
 */
reason: string | null, displayServer: DisplayServer, features: Features, };
