// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point in logical (CSS) pixels from the top-left of the webview.
 */
export type Position = { x: number, y: number, };
