// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DragEnded } from "./DragEnded";

/**
 * What `start_drag` did.
 */
export type StartDragReport = { 
/**
 * Identifies the drag in `DragEnded`.
 */
id: number, 
/**
 * Set on Windows, where the command resolves only when the drag has finished; null on Linux, where the drag runs on after the command resolves and `native-dnd://drag-ended` reports it.
 */
ended: DragEnded | null, };
