// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DragAction } from "./DragAction";
import type { DragIcon } from "./DragIcon";

/**
 * Arguments of `start_drag`.
 */
export type StartDragRequest = { 
/**
 * The `file://` URIs to offer.
 */
uris: Array<string>, 
/**
 * The actions the drop target may choose from; at least one.
 */
actions: Array<DragAction>, 
/**
 * The image dragged with the pointer. Used on Linux; Windows draws its own.
 */
icon: DragIcon | null, };
