// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One application that can open a type.
 */
export type App = { 
/**
 * A stable handle: the desktop-file id on Linux (`org.gnome.eog.desktop`), the handler's name on Windows. Pass it to `openWith`, `setDefault` and `appIconUrl`; its form is otherwise opaque.
 */
id: string, 
/**
 * The name to show.
 */
name: string, 
/**
 * The name of the application's icon in the icon theme, when it has one. The picture itself comes from the `appicon://` scheme, by `id`.
 */
icon: string | null, 
/**
 * The command line the application is started with, for a tooltip. Never run by the plugin itself.
 */
execHint: string | null, };
