// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { App } from "./App";

/**
 * The applications for one type, or for several types at once.
 */
export type Handlers = { 
/**
 * The type every URI has. When the URIs have different types, this is the first one and `mixed` is set; the lists then hold only the applications that open every type.
 */
mime: string, mixed: boolean, 
/**
 * What opens the type when nothing is chosen. Not repeated in `recommended`.
 */
default: App | null, 
/**
 * Applications registered for the type, in the system's order.
 */
recommended: Array<App>, 
/**
 * Applications that can open it without being registered for it, by name.
 */
others: Array<App>, };
