// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one call failed. Serialised as `{ "kind": "noHandler", "mime": "image/png" }`, so the front end can branch on `kind`.
 */
export type MimeAppsError = { "kind": "appNotFound" } | { "kind": "noHandler", mime: string, } | { "kind": "invalidUri", uri: string, } | { "kind": "empty" } | { "kind": "cancelled" } | { "kind": "unsupported" } | { "kind": "failed", message: string, };
