// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";
import type { Flavour } from "./Flavour";
import type { Reason } from "./Reason";

/**
 * What the plugin can do on the running system.
 */
export type PluginStatus = { 
/**
 * True when at least one feature is available.
 */
available: boolean, 
/**
 * Why the first unavailable feature is; absent when everything works.
 */
reason: Reason | null, message: string | null, flavour: Flavour, features: Array<FeatureStatus>, 
/**
 * The `mimeapps.list` files that exist, from the one that wins to the one that loses (Linux only; empty elsewhere). Read-only: it explains where a default comes from.
 */
associationFiles: Array<string>, };
