// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a feature is unavailable. A code the front end can branch on; `message` beside it is a sentence for people.
 */
export type Reason = "flatpak-sandbox" | "no-system-chooser" | "managed-by-system" | "no-display" | "no-icon-theme" | "not-implemented" | "unsupported-platform";
