// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the system knows about a type.
 */
export type TypeInfo = { 
/**
 * The content type: a MIME type on Linux (`image/png`), the registered content type or, failing that, the extension (`.png`) on Windows.
 */
mime: string, 
/**
 * A phrase for people ("PNG image"). Falls back to the type itself.
 */
description: string, 
/**
 * The name of the type's icon in the icon theme, when it has one.
 */
icon: string | null, };
