// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reason } from "./Reason";

/**
 * Whether one feature of the plugin works on this system.
 */
export type FeatureStatus = { 
/**
 * One of `cache`, `builtin`, `external` or `shell`.
 */
name: string, available: boolean, reason: Reason | null, 
/**
 * How many of something the feature found: the thumbnailers for `external`.
 */
count: number | null, };
