// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";
import type { Flavour } from "./Flavour";
import type { Reason } from "./Reason";

/**
 * What the plugin can do on the running system.
 */
export type PluginStatus = { 
/**
 * True when at least one feature can make or serve thumbnails.
 */
available: boolean, 
/**
 * Why nothing is available; absent otherwise.
 */
reason: Reason | null, flavour: Flavour, features: Array<FeatureStatus>, };
