// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasonKind } from "./ReasonKind";

/**
 * Why a feature does not work: a kind to branch on and a sentence to show.
 */
export type Reason = { kind: ReasonKind, message: string, };
