// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a request was skipped rather than failed: nothing is wrong, the plugin chose not to (or cannot) make this thumbnail.
 */
export type SkipWhy = "remote" | "tooLarge" | "cloud" | "noGenerator" | "unsupported";
