// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipWhy } from "./SkipWhy";

/**
 * What happened to one requested thumbnail, sent through the request's channel. A cancelled request gets nothing more.
 */
export type ThumbEvent = { "kind": "ready", key: string, url: string, } | { "kind": "failed", key: string, reason: string, } | { "kind": "skipped", key: string, why: SkipWhy, };
