// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The four sizes of the freedesktop.org Thumbnail Managing Standard. A thumbnail fits within a square of `pixels()` on each side and is never scaled up.
 */
export type ThumbSize = "normal" | "large" | "x-large" | "xx-large";
