// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThumbSize } from "./ThumbSize";

/**
 * One thumbnail the caller wants.
 */
export type ThumbRequest = { 
/**
 * The caller's own handle for the item, returned in every event for it. Requests with the same key are one job.
 */
key: string, 
/**
 * The absolute path of a local file.
 */
path: string, size: ThumbSize, 
/**
 * The file's modified time in milliseconds since the Unix epoch; a cached thumbnail made from another time is stale.
 */
mtimeMs: number, };
