// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One appearance preference whose availability is reported.
 */
export type AppearanceFeature = "colourScheme" | "accent" | "contrast" | "reducedMotion" | "reducedTransparency" | "textScale" | "iconTheme";
