// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceFeature } from "./AppearanceFeature";
import type { AppearanceSource } from "./AppearanceSource";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Whether one appearance preference could be read, and from where.
 */
export type AppearanceFeatureStatus = { feature: AppearanceFeature, available: boolean, 
/**
 * The source the value comes from; absent when unavailable.
 */
source: AppearanceSource | null, 
/**
 * Why the preference is unavailable; absent when it works.
 */
reason: UnavailableReason | null, 
/**
 * Human-readable detail for `reason`, such as the failing key or error.
 */
detail: string | null, };
