// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSources } from "./AppearanceSources";
import type { ColourScheme } from "./ColourScheme";
import type { Contrast } from "./Contrast";

/**
 * What `get_appearance` resolves to and the change event carries: the preferences plus a
 * revision. The revision starts at 1 and increases whenever a value or a source changes; the
 * JSON is the preferences object with a `revision` field added.
 */
export type AppearancePreferences = { revision: number, colourScheme: ColourScheme, 
/**
 * The accent colour as lower-case `#rrggbb`; absent when the system has none.
 */
accent: string | null, contrast: Contrast, reducedMotion: boolean, reducedTransparency: boolean, 
/**
 * The text scale as a multiplier, where 1 is the default size.
 */
textScale: number, 
/**
 * The name of the icon theme, as the desktop spells it.
 */
iconTheme: string | null, sources: AppearanceSources, };
