// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSources } from "./AppearanceSources";
import type { ColourScheme } from "./ColourScheme";
import type { Contrast } from "./Contrast";

/**
 * The appearance preferences of the running desktop.
 *
 * A preference nothing could answer holds a neutral value (`noPreference`, `null`, `normal`,
 * `false`, a text scale of 1); its entry in `sources` is then absent and `get_status` says why.
 */
export type AppearanceValues = { colourScheme: ColourScheme, 
/**
 * The accent colour as lower-case `#rrggbb`; absent when the system has none.
 */
accent: string | null, contrast: Contrast, reducedMotion: boolean, reducedTransparency: boolean, 
/**
 * The text scale as a multiplier, where 1 is the default size.
 */
textScale: number, 
/**
 * The name of the icon theme, as the desktop spells it.
 */
iconTheme: string | null, sources: AppearanceSources, };
