// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSource } from "./AppearanceSource";

/**
 * The preference sources that won, one per preference; absent where nothing could be read.
 */
export type AppearanceSources = { colourScheme: AppearanceSource | null, accent: AppearanceSource | null, contrast: AppearanceSource | null, reducedMotion: AppearanceSource | null, reducedTransparency: AppearanceSource | null, textScale: AppearanceSource | null, iconTheme: AppearanceSource | null, };
