// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one appearance preference was read from.
 */
export type AppearanceSource = "portal" | "gsettings" | "kdeGlobals" | "uiSettings" | "accessibilitySettings" | "registry";
