// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowButton } from "./WindowButton";

/**
 * Titlebar buttons on each side of the title, in display order.
 */
export type ButtonLayout = { start: Array<WindowButton>, end: Array<WindowButton>, };
