// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the user prefers a light or a dark look.
 */
export type ColourScheme = "light" | "dark" | "noPreference";
