// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The desktop environment the preferences were read for.
 */
export type DesktopEnvironment = "gnome" | "kde" | "cinnamon" | "mate" | "xfce" | "windows" | "macos" | "unknown";
