// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the reported preferences came from.
 */
export type LayoutSource = "portal" | "kwinConfig" | "gsettings" | "xfconf" | "platform" | "default";
