// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one palette colour was read from.
 */
export type PaletteSource = "gtkTheme" | "kdeGlobals" | "portal" | "uiSettings" | "sysColor";
