// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One colour of the palette.
 */
export type PaletteColour = "windowBackground" | "windowForeground" | "viewBackground" | "viewForeground" | "surfaceBackground" | "selectionBackground" | "selectionForeground" | "border" | "focus" | "warning" | "error" | "success";
