// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteSource } from "./PaletteSource";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Whether the palette could be read here, and from where.
 */
export type PaletteStatus = { available: boolean, source: PaletteSource | null, reason: UnavailableReason | null, detail: string | null, };
