// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteSource } from "./PaletteSource";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * One palette colour with the source that supplied it, or the typed reason it is unavailable.
 */
export type PaletteEntry = { 
/**
 * The colour as lower-case `#rrggbb`; absent when unavailable.
 */
colour: string | null, 
/**
 * The source the colour comes from; absent when unavailable.
 */
source: PaletteSource | null, 
/**
 * Why the colour is unavailable; absent when it works.
 */
reason: UnavailableReason | null, 
/**
 * Human-readable detail for `reason`, such as the names the theme lacks.
 */
detail: string | null, };
