// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteEntry } from "./PaletteEntry";

/**
 * Every colour of the palette. An entry nothing could answer has no colour and says why.
 */
export type PaletteColours = { 
/**
 * The window's own background (a GTK theme's `theme_bg_color`).
 */
windowBackground: PaletteEntry, 
/**
 * Text on the window background.
 */
windowForeground: PaletteEntry, 
/**
 * The background of content views, lists and text fields (`theme_base_color`).
 */
viewBackground: PaletteEntry, 
/**
 * Text on a view.
 */
viewForeground: PaletteEntry, 
/**
 * The background of raised surfaces: popovers, cards, buttons.
 */
surfaceBackground: PaletteEntry, selectionBackground: PaletteEntry, 
/**
 * Text on the selection.
 */
selectionForeground: PaletteEntry, border: PaletteEntry, 
/**
 * The focus ring or focus decoration.
 */
focus: PaletteEntry, warning: PaletteEntry, error: PaletteEntry, success: PaletteEntry, 
/**
 * The top of the title bar (a GTK theme's `headerbar_bg_color`, KDE's header background). A
 * platform or theme with no title bar colour reports a miss, and the title bar stays flat.
 */
titleBarBackground: PaletteEntry, 
/**
 * The bottom of the title bar, where the theme shades it in two tones. Only present with a
 * top colour.
 */
titleBarBackgroundEnd: PaletteEntry, };
