// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteEntry } from "./PaletteEntry";
import type { PaletteStatus } from "./PaletteStatus";

/**
 * What `get_palette` resolves to and the change event carries: the colours plus a revision. The
 * revision starts at 1 and increases whenever a colour or its source changes; the JSON is the
 * colours object with a `revision` field and the `status` added.
 */
export type Palette = { revision: number, status: PaletteStatus, 
/**
 * The window's own background (a GTK theme's `theme_bg_color`).
 */
windowBackground: PaletteEntry, 
/**
 * Text on the window background.
 */
windowForeground: PaletteEntry, 
/**
 * The background of content views, lists and text fields (`theme_base_color`).
 */
viewBackground: PaletteEntry, 
/**
 * Text on a view.
 */
viewForeground: PaletteEntry, 
/**
 * The background of raised surfaces: popovers, cards, buttons.
 */
surfaceBackground: PaletteEntry, selectionBackground: PaletteEntry, 
/**
 * Text on the selection.
 */
selectionForeground: PaletteEntry, border: PaletteEntry, 
/**
 * The focus ring or focus decoration.
 */
focus: PaletteEntry, warning: PaletteEntry, error: PaletteEntry, success: PaletteEntry, };
