// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceFeatureStatus } from "./AppearanceFeatureStatus";

/**
 * Whether the plugin could read the platform's preferences, and how.
 *
 * `available` is true when the titlebar preferences or any appearance preference could be read;
 * `reason` says why the titlebar preferences could not. `features` names the titlebar sources
 * that worked (`portal`, `kwin-config`, ...) followed by the appearance features that did
 * (`colourScheme`, ...), and `appearance` reports every appearance feature with its reason when
 * it does not work.
 */
export type PluginStatus = { available: boolean, reason: string | null, features: Array<string>, appearance: Array<AppearanceFeatureStatus>, };
