// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceFeatureStatus } from "./AppearanceFeatureStatus";
import type { PaletteStatus } from "./PaletteStatus";

/**
 * Whether the plugin could read the platform's preferences, and how.
 *
 * `available`, `reason` and `features` describe the titlebar preferences only: `available` is
 * true when a titlebar source answered, `reason` says why none did, and `features` names the
 * sources that worked (`portal`, `kwin-config`, ...). The appearance preferences are reported
 * separately: `appearanceAvailable` is true when any appearance feature works, and `appearance`
 * reports every appearance feature with its reason when it does not. `palette` says whether the
 * colour palette (`get_palette`) can be read.
 */
export type PluginStatus = { available: boolean, reason: string | null, features: Array<string>, appearanceAvailable: boolean, appearance: Array<AppearanceFeatureStatus>, 
/**
 * Whether the colour palette can be read, from where, and why not when it cannot.
 */
palette: PaletteStatus, };
