// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the plugin could read the platform's preferences, and how.
 */
export type PluginStatus = { available: boolean, reason: string | null, features: Array<string>, };
