// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonLayout } from "./ButtonLayout";
import type { DesktopEnvironment } from "./DesktopEnvironment";
import type { LayoutSource } from "./LayoutSource";
import type { TitlebarActions } from "./TitlebarActions";

/**
 * The preferences stamped with a revision, so a consumer can discard a reading that is older
 * than one it already has. The revision starts at 1 and increases whenever the preferences
 * change; the JSON is the preferences object with a `revision` field added.
 */
export type TitlebarSnapshot = { revision: number, buttonLayout: ButtonLayout, actions: TitlebarActions, desktopEnvironment: DesktopEnvironment, source: LayoutSource, };
