// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An action the desktop runs for a titlebar gesture.
 */
export type TitlebarAction = "toggleMaximise" | "toggleMaximiseHorizontally" | "toggleMaximiseVertically" | "toggleShade" | "minimise" | "lower" | "menu" | "none";
