// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonLayout } from "./ButtonLayout";
import type { DesktopEnvironment } from "./DesktopEnvironment";
import type { LayoutSource } from "./LayoutSource";
import type { TitlebarActions } from "./TitlebarActions";

/**
 * The titlebar preferences of the running desktop.
 */
export type TitlebarPreferences = { buttonLayout: ButtonLayout, actions: TitlebarActions, desktopEnvironment: DesktopEnvironment, source: LayoutSource, };
