// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TitlebarAction } from "./TitlebarAction";

/**
 * Actions bound to titlebar gestures.
 */
export type TitlebarActions = { doubleClick: TitlebarAction, middleClick: TitlebarAction, rightClick: TitlebarAction, };
