// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A button that can appear in a window titlebar.
 */
export type WindowButton = "appMenu" | "windowMenu" | "minimise" | "maximise" | "close" | "keepAbove" | "keepBelow" | "shade" | "stick" | "help";
