// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one feature of the plugin works on this system.
 */
export type FeatureStatus = { 
/**
 * Always `elevate` for now.
 */
name: string, available: boolean, 
/**
 * Why the feature is unavailable; absent when it works. Plain text for the person, and never a path.
 */
reason: string | null, };
