#!/usr/bin/env bash
# Check the committed ts-rs bindings match what the Rust types generate
#
# (c) Copyright 2026 Liminal HQ, Scott Morris
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Every generated directory is snapshotted, deleted, regenerated by the Rust tests, and compared.
# Deleting first matters: ts-rs only writes files for types that still exist and never removes a
# stale one, so a removed or renamed type would otherwise leave its old file behind and the
# comparison would miss that the committed copy is out of date. Exits 1 and lists the differences
# on drift; on drift the regenerated files are left in place, so `git diff` shows the change.
set -euo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || dirname "$(dirname "${BASH_SOURCE[0]}")")"

# Add a directory here (and its crate to CRATES) whenever a crate or plugin exports bindings.
DIRS=(
  "apps/waypoint/src/domain/protocol/generated"
  "plugins/system-appearance/guest-js/bindings"
  "plugins/window-manager/guest-js/bindings"
)
CRATES=(waypoint-protocol tauri-plugin-system-appearance tauri-plugin-window-manager)

snapshot="$(mktemp -d)"
trap 'rm -rf "${snapshot}"' EXIT

for dir in "${DIRS[@]}"; do
  mkdir -p "${snapshot}/${dir}"
  cp -r "${dir}/." "${snapshot}/${dir}/"
  rm -rf "${dir}"
done

cargo_args=()
for crate in "${CRATES[@]}"; do cargo_args+=(-p "${crate}"); done
cargo test "${cargo_args[@]}" --quiet >/dev/null

drift=0
for dir in "${DIRS[@]}"; do
  if ! diff -rq "${snapshot}/${dir}" "${dir}"; then
    drift=1
  fi
done

if [ "${drift}" -ne 0 ]; then
  echo
  echo "The committed bindings are out of date. Regenerate them with 'bun run bindings' and commit the result."
  exit 1
fi

echo "Generated bindings are up to date: ${#DIRS[@]} directories checked."
