// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reason } from "./Reason";

/**
 * Whether one feature of the plugin works on this system.
 */
export type FeatureStatus = { 
/**
 * One of `list`, `mount`, `unmount`, `eject`, `unlock` or `watch`.
 */
name: string, available: boolean, 
/**
 * Why the feature is unavailable; absent when it works.
 */
reason: Reason | null, 
/**
 * A sentence that explains the reason; absent when the feature works.
 */
message: string | null, };
