// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a feature is unavailable. A code the front end can branch on; `message` beside it is a sentence for people.
 */
export type Reason = "no-system-bus" | "udisks2-missing" | "flatpak-sandbox" | "udisks2-failed" | "unsupported-platform" | "not-supported" | "no-keyring" | "keyring-locked" | "disabled" | "not-configured";
