// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reason } from "./Reason";

/**
 * What became of the request to remember a passphrase, which `unlock` reports beside the new volume: unlocking worked either way.
 */
export type RememberOutcome = { "state": "notAsked" } | { "state": "remembered" } | { "state": "failed", reason: Reason, message: string, };
