// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RememberOutcome } from "./RememberOutcome";

/**
 * What `unlock` returns: the id of the volume that appeared (mount it next) and what became of a request to remember the passphrase.
 */
export type Unlocked = { id: string, remember: RememberOutcome, };
