// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Volume } from "./Volume";

/**
 * The payload of `volumes://changed`: the whole list after the change, with a revision that only ever grows.
 */
export type VolumesChanged = { 
/**
 * Starts at 1 with the first list and grows by one with each change. An event older than the revision already seen is stale and can be ignored.
 */
revision: number, volumes: Array<Volume>, };
