// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VolumeKind } from "./VolumeKind";

/**
 * One volume: a disk, partition, drive letter, mount or network share, and what can be done to it.
 */
export type Volume = { 
/**
 * A stable handle for the volume, valid for the commands `mount`, `unmount`, `eject`, `unlock` and `refreshSpace` while the volume exists. Its form is opaque to callers.
 */
id: string, 
/**
 * The name to show: the file system label, or a description when it has none.
 */
label: string, kind: VolumeKind, 
/**
 * The file system type as the system names it (`ext4`, `ntfs`, `crypto_LUKS`, `nfs4`), when known.
 */
fileSystem: string | null, 
/**
 * Where it is mounted: a folder on Linux, a drive root (`E:\`) on Windows. Absent when it is not mounted.
 */
mountPoint: string | null, 
/**
 * A URL for a network volume (`smb://server/share`), when one can be made.
 */
uri: string | null, 
/**
 * Size in bytes. For a volume that is not mounted, the size of the device when known.
 */
total: number | null, 
/**
 * Free bytes available to this user. Absent when the volume is not mounted, when measuring it timed out, or when it was not measured (network volumes are measured only when asked).
 */
free: number | null, canMount: boolean, canUnmount: boolean, canEject: boolean, 
/**
 * The drive can be powered off after it is ejected (`eject` does that as well).
 */
canPowerOff: boolean, 
/**
 * An encrypted volume that must be unlocked before it can be mounted.
 */
locked: boolean, 
/**
 * A fixed, internal device (the system's own disks), as opposed to something plugged in or remote.
 */
isSystem: boolean, 
/**
 * The device node (`/dev/sdb1`) or, for a mapped drive, the remote name (`\\server\share`).
 */
device: string | null, 
/**
 * The UUID of an encrypted volume's container (its LUKS header), locked or unlocked: the same every time it is plugged in, which `id` is not. Absent for anything else.
 */
uuid: string | null, 
/**
 * A passphrase for this encrypted volume is kept in the keyring, so it unlocks by itself when it is plugged in. False when none is, when remembering is off, or when the keyring cannot be asked.
 */
remembered: boolean, };
