// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What sort of volume this is, which decides its icon and its place in a list.
 */
export type VolumeKind = "internal" | "removable" | "optical" | "network" | "loop" | "encrypted";
