// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one action on a volume failed. Serialised as `{ "kind": "busy", "by": "bash" }`, so the front end can branch on `kind`.
 */
export type VolumesError = { "kind": "busy", by: string | null, } | { "kind": "notAuthorised" } | { "kind": "wrongPassphrase" } | { "kind": "unsupported" } | { "kind": "notFound" } | { "kind": "io", message: string, };
