// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why one action on a secret failed. Serialised as `{ "kind": "locked" }`, so the front end can branch on `kind`. No variant carries a secret, and `Failed` carries only a library's own description of what went wrong.
 */
export type SecretsError = { "kind": "noKeyring" } | { "kind": "locked" } | { "kind": "dismissed" } | { "kind": "unsupported" } | { "kind": "invalid", field: string, } | { "kind": "failed", message: string, };
