// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretKind } from "./SecretKind";

/**
 * Names one secret: what it is for (`service`: `sftp`, `volume`), whose it is (`account`: a connection or a device) and its kind. Names are not secret, but they are not logged either: an account can be a user name.
 */
export type SecretId = { service: string, account: string, kind: SecretKind, };
