// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What sort of secret this is. It is part of the identity of a secret, so one account can hold a password and the passphrase of its key side by side.
 */
export type SecretKind = "password" | "passphrase" | "token" | "key";
