// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `begin` did.
 */
export type BeginState = "following" | "noGhost" | "alreadyActive";
