// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeginState } from "./BeginState";

/**
 * The result of `begin`.
 */
export type BeginReport = { state: BeginState, };
