// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent to a window that was sent `drag-hover` when the payload leaves it or is dropped on it.
 */
export type DragLeave = { 
/**
 * The label of the window the payload left (the receiver).
 */
window: string, };
