// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent to a window while a toplevel drag's payload is over it.
 */
export type DragHover = { 
/**
 * The label of the window the payload is over (the receiver).
 */
window: string, 
/**
 * The pointer in logical pixels from the top-left of the window's content.
 */
x: number, y: number, 
/**
 * The id of the registered region under the pointer, if any.
 */
region: string | null, 
/**
 * The drag's opaque payload, as `begin_toplevel_drag` was given it.
 */
payload: unknown, };
