// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hit } from "./Hit";
import type { Point } from "./Point";

/**
 * What `end` found.
 */
export type DropReport = { 
/**
 * The cursor in physical pixels, or null where the system does not report it.
 */
cursor: Point | null, 
/**
 * The scale factor of the window that began the drag, for converting `cursor` to logical pixels.
 */
scaleFactor: number, 
/**
 * True if the cursor value had stopped changing while a button was held, so `cursor` may be out of date.
 */
cursorStale: boolean, 
/**
 * The topmost registered region under the cursor; always null for a cancelled drag and where hit-testing is unavailable.
 */
hit: Hit | null, };
