// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered region that the cursor was over.
 */
export type Hit = { 
/**
 * The label of the window that registered the region.
 */
window: string, 
/**
 * The `id` of the region.
 */
region: string, 
/**
 * The cursor in logical pixels from the top-left of that window's content, the origin its regions are measured from.
 */
x: number, y: number, };
