// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent to a window when a toplevel drag's payload is dropped on it.
 */
export type PayloadDropped = { 
/**
 * The label of the window the payload was dropped on (the receiver).
 */
window: string, 
/**
 * The drag's payload, parsed from what the source offered.
 */
payload: unknown, 
/**
 * Where it was dropped, in logical pixels from the top-left of the window's content.
 */
x: number, y: number, 
/**
 * The id of the region the drop was over, when it was over one of the window's registered regions.
 */
region: string | null, };
