// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent to a window when a toplevel drag's payload is dropped on it.
 */
export type PayloadDropped = { 
/**
 * The label of the window the payload was dropped on (the receiver).
 */
window: string, 
/**
 * The drag's payload, parsed from what the source offered.
 */
payload: unknown, };
