// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnavailableFeature } from "./UnavailableFeature";

/**
 * Whether the plugin can do anything on this system, and which features work.
 */
export type PluginStatus = { 
/**
 * True if at least one feature works.
 */
available: boolean, 
/**
 * Why nothing works, when `available` is false.
 */
reason: string | null, 
/**
 * The features that work: `ghost`, `cursor_follow`, `window_position`, `hit_test` and `toplevel_drag`.
 */
features: Array<string>, 
/**
 * The features that do not work, each with its reason.
 */
unavailable: Array<UnavailableFeature>, };
