// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point in physical pixels on the virtual screen, or in logical pixels where a field says so.
 */
export type Point = { x: number, y: number, };
