// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rectangle in logical pixels, relative to the top-left of the content area of the window that registered it.
 */
export type Region = { 
/**
 * Returned in `DropReport.hit` so the caller knows which region was hit.
 */
id: string, x: number, y: number, width: number, height: number, };
