// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A size in logical pixels.
 */
export type Size = { width: number, height: number, };
