// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `begin_toplevel_drag` did.
 */
export type ToplevelBeginState = "started" | "unavailable" | "alreadyActive" | "failed";
