// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent to the window that began a toplevel drag when the compositor has taken it.
 */
export type ToplevelDragStarted = { 
/**
 * The label of the window being dragged.
 */
window: string, 
/**
 * The drag's opaque payload, as `begin_toplevel_drag` was given it.
 */
payload: unknown, };
