// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToplevelBeginState } from "./ToplevelBeginState";

/**
 * The result of `begin_toplevel_drag`.
 */
export type ToplevelBeginReport = { state: ToplevelBeginState, 
/**
 * Why nothing started, when `state` is not `started`.
 */
reason: string | null, };
