// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToplevelOutcome } from "./ToplevelOutcome";

/**
 * Sent when a toplevel drag ends, to the window that began it and to the window that was dragged. A late listener can ask for it with `take_toplevel_drag_result`.
 */
export type ToplevelDragEnded = { 
/**
 * The label of the window that was dragged.
 */
window: string, 
/**
 * The label of the window that began the drag.
 */
source: string, outcome: ToplevelOutcome, 
/**
 * The window the payload was dropped on, for `dropped-on-window`.
 */
target: string | null, 
/**
 * The drag's opaque payload, as `begin_toplevel_drag` was given it.
 */
payload: unknown, 
/**
 * Why the drag failed, for `failed`.
 */
reason: string | null, };
