// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a toplevel drag ended.
 */
export type ToplevelOutcome = "dropped-on-window" | "dropped-elsewhere" | "cancelled" | "failed";
