// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A feature that does not work on this system, and why.
 */
export type UnavailableFeature = { feature: string, reason: string, };
